### ISSUE TITLE
Is it possible to use this library for absolutely or fixed positioned images?

### ISSUE THREAD

**Issue by martinkz** [geosigno/simpleParallax.js#103]
I want the image to be in the background, overlayed by the page content. Does the library allow this? Right now if I set the position of the image to absolute or fixed, the parallax effect doesn't work.

**Comment by geosigno** [comment]
simpleParallax does not fit in this case. It was built to handle parallax on the img tag element and not the background image. The second approach has already been addressed by many plugins or pure css.
