### ISSUE TITLE
Change Viewbox?

### ISSUE THREAD

**Issue by sahilmtayade** [geosigno/simpleParallax.js#105]
I want to change the view box of the image without changing the size. Is there an easy way to do this?

Right now to achieve what I want I have to use overflow:true and z-index. This is because I cannot change max-transition to over 100, and I can't change the speed.

**Comment by sahilmtayade** [comment]
When using overflow: true, the scale property has no effect

**Comment by geosigno** [comment]
The scale has effect even with the overflow set at true. It will enlarge the transition zone.
