### ISSUE TITLE
Parallax stops when container is halfway off screen

### ISSUE THREAD

**Issue by 75th** [geosigno/simpleParallax.js#123]
When a parallax container is scrolled 50% off the top of the screen, the parallax animation just stops happening.

This is visible even on simpleparallax.com with the [examples](https://simpleparallax.com/#examples), though strangely not with the banner above [the Installation section.](https://simpleparallax.com/#installation). It's easiest to see on the examples with horizontal movement.

**Comment by geosigno** [comment]
I guess the issue is fixed with the new example section. If not, please fell free to re-open.
