### ISSUE TITLE
Not scrolling

### ISSUE THREAD

**Issue by DarioLopes** [geosigno/simpleParallax.js#36]
The plugin indeed put all inline style but scroll doesn't change anything... Any guess?

**Comment by fransoudelaar** [comment]
> The plugin indeed put all inline style but scroll doesn't change anything... Any guess?

Do you use an absolute positioned image? It seems like it doesn't work if the image has a `position: 'absolute'`.

**Comment by DarioLopes** [comment]
Hi Frans,

well, it was because I wrap my images with a <figure> elements instead of a <picture>+<source>

It's mentionned that it's a necessity in the main landing page of the plugin but I didn't clearly see it the first time.

Thanks!

**Comment by geosigno** [comment]
I don't sure I understand what was the issue in the first place? Your images were wrapped into what?
