### ISSUE TITLE
Feature: make it also work with videos

### ISSUE THREAD

**Issue by Teddytrombone** [geosigno/simpleParallax.js#41]
It would be great if we could use this library also for applying a parallax effect on `<video />` tags.
In addition maybe it would also be possible to use it for youtube videos?

**Comment by geosigno** [comment]
This should be doable yes, at least for HTML5 video. Let me think about that.

**Comment by geosigno** [comment]
Support for video has been added with [5.4.0](https://github.com/geosigno/simpleParallax.js/releases/tag/5.4.0).

Please re-open this issue if needed.
