### ISSUE TITLE
horribly laggy on iOS Safari

### ISSUE THREAD

**Issue by deflectn** [geosigno/simpleParallax.js#44]
Tested on iOS 13.3.1/13.4 iPhone 6/SE/7/8

Dude I think a parallax lib is a bit unnecessary but why not. I guess it's primarily for Webdesigners.  Whatever it's very laggy on mobile safari as mentioned on [Reddit](https://www.reddit.com/r/javascript/comments/fx4lqt/simpleparallaxjs_the_easiest_way_to_get_a/fms5pjp/?utm_source=share&utm_medium=ios_app&utm_name=iossmf). Have a look on it 😉

**Comment by geosigno** [comment]
Thanks for your time and contribution despite your lack of interest :)

The issue was due to the demo website, some conflict with the 100vh of the header. This should be good now. Take and look and let me know if you are still facing it.

Thanks!

**Comment by snicholls-orm** [comment]
this happens on my own project,  it is jerky on ios, can we have a disable option for ios??

**Comment by geosigno** [comment]
Sorry to hear that. Can you share some video or a link so I can check?

**Comment by snicholls-orm** [comment]
> Sorry to hear that. Can you share some video or a link so I can check?

thanks, its https://tinyurl.com/red2rbx - if you scroll down in mobile on ios safari the full width banners (with the letters in) are jerky on scroll.  is there a way to disable the effect on mobile / ios?

**Comment by geosigno** [comment]
Look good on my iPhone 8 Safari [here](https://share.getcloudapp.com/jkuldrpG)

**Comment by geosigno** [comment]
I can see comments have been deleted, i guess the issue is fixed then.

**Comment by deflectn** [comment]
I will later upload a video. The issue occurs on the demo page. The images are stuttering by random up and down scrolling. Make sure you do not have any experimental flags set.

**Comment by geosigno** [comment]
Please send the video so I can have a look.
