### ISSUE TITLE
Adding information about supported browsers

### ISSUE THREAD

**Issue by miestassimon** [geosigno/simpleParallax.js#46]
Please, let users know on the README page, that IE browsers are not supported. It used `Element.closest()` and Intersection Observer API. It needs a polyfill. A polyfilled version would be the best :)

Thank you!

**Comment by geosigno** [comment]
You're right, supported browsers section added in [5.5.0](https://github.com/geosigno/simpleParallax.js/releases/tag/5.5.0).

Thanks!
