### ISSUE TITLE
Use on figure element

### ISSUE THREAD

**Issue by jd61284** [geosigno/simpleParallax.js#48]
hi , 
Would it be possible to use this library  for applying a parallax effect on `<figure>` element 
So the parallax could work on the` <img>` and `<figcaption>` tag at the same time ?
Here is an exemple for the markup
```
 
<figure>
 <img src="bubbles-work.jpeg">
 <figcaption>Bubbles at work</figcaption>
</figure>
```

Thanks

**Comment by geosigno** [comment]
Hi,
simpleParallax uses a scale transformation to create the parallax effect, it may looks weird to scale a text.
What is the problem with the figcaption, is the image overlapping it?

**Comment by jd61284** [comment]
When i want to use it with the setting "overflow: true', i can only apply it to the img and the figcaption stays in a kind of sticky position

**Comment by geosigno** [comment]
As per design, simpleParallax will not work on texts. 
In your case, i would use the _overflow_ at _false_. Or use the _overflow_ at _true_ with a _right_ or _left_ _direction_.
