### ISSUE TITLE
Dynamic Page Height Issue 

### ISSUE THREAD

**Issue by royshoa** [geosigno/simpleParallax.js#50]
Hi, 

**Details**
When the page height is changing dynamically after initialized simpleParallax the calculations are wrong. 

**Reproduce**
- Create a div above a sinmpleParallax img tag: `<div class="space" style="height: 100px;"></div>`
- Initialize simpleParallax on the image tag 
- Change the div height to `500px` 
- See the results 

**Solution**
If you can add a Refresh function that recalculate the positions anyone can call it when he detect a change at this website.

**Comment by geosigno** [comment]
Refresh method added in [5.5.0](https://github.com/geosigno/simpleParallax.js/releases/tag/5.5.0)

Thanks!
