### ISSUE TITLE
Parallax Without Scale

### ISSUE THREAD

**Issue by royshoa** [geosigno/simpleParallax.js#52]
Hi, 

I really like simpleParallax solution for using Parallax but I really like to get the same effect without Scaling the image. 

I sow that when using the `overflow: true` property the Parallax is working but the image us bot displayed as scaled, so I try to use it and I added `overflow: false` CSS to the image parent to prevent the image overlap with your content, its works but there is a bug with the calculations and the image go out from its container a little. 

If there is any fix for that issue it will be perfect! 

![1756922ae61b7430b5de547f9e8b1e8f](https://user-images.githubusercontent.com/4424594/83962052-55732800-a8a2-11ea-96f8-6ee71e19a413.gif)

**Comment by geosigno** [comment]
Hello,

I'm not sure to understand what is the issue nor what you are trying to do.

Can you tell me what you want to achieve exactly? About the issue, can you share a codepen?

yhanks.

**Comment by royshoa** [comment]
I am trying to implement SimpleParallax plugin without Scaling the Image , when I used the `overflow:true` property SimpleParallax do not scale the preview image. 

At the GIF above you can see a Blue color, this is because the image overlap its container, I just need it to behave like `background-attachment: fixed `. 

[JSFiddle Example](https://jsfiddle.net/royshoa/4vocd1j3/32/)

![Scroll Down & Up Fast to see the issue](https://user-images.githubusercontent.com/4424594/84002843-bfa6ce00-a971-11ea-9bb6-d43fb7121b14.png)

**Comment by geosigno** [comment]
simpleParallax uses the scale parameter to have a parallax on an image tag without any layout overlapping. Unfortunately what you are trying to achieve will not work with this plugin. 

Why don't you want to use the scale parameter?

**Comment by royshoa** [comment]
It looks like you do not understand me, when you use the Scale its increasing he image size, its not looks good. I didn't told you that I don't like to use the scale parameter, I told you that I like to use the `overflow: true` parameter and that you have a bug when I use it a you can see in the JSFiddle.

Anyway, can you just fix the bug here, as you can see when scrolling there is a blue background: 
[Link](https://jsfiddle.net/royshoa/4vocd1j3/32/)

**Comment by geosigno** [comment]
1- if you set the overflow at true, it will move the image out of its natural flow, as explaining in the [doc](https://github.com/geosigno/simpleParallax.js#overflow---boolean---see-example) - this is no a bug.
2- I understand the scale may decrease the image quality, to cater for this you can increase the image size.

> Theoretically, we can apprehend the fact that if the scale is applied to an image, we will lose quality.
> In practice, this is hardly noticeable if the scale is set at 1.3 (which is the default value of the library). And even less if you cater for this by adding an image with a bigger size — meaning if your image is 500px and you want to apply a 1.5 scale, compensate by using a 750px width image.
from [case study](https://itnext.io/case-study-create-a-parallax-effect-directly-on-img-tags-with-javascript-35b8daf81471).
