### ISSUE TITLE
 IParallaxSettings.customContainer?: boolean Type 'string' is not assignable to type 'boolean'

### ISSUE THREAD

**Issue by Joshanity17** [geosigno/simpleParallax.js#58]
I tried to use the code provided from `README.md`; however, the code breaks because on the compiled library, `customContainer` is a `boolean` type, but on the `README`, it is supplied with a string value.

**Comment by geosigno** [comment]
Are you using the latest version? Because this should have been fixed with this [commit](https://github.com/geosigno/simpleParallax.js/commit/6be25bec2bb77011218bf5b6aaba0bf76f5b3a40).

**Comment by geosigno** [comment]
I closing this issue for now, let me know if you are still encountering it.
