### ISSUE TITLE
Option Request

### ISSUE THREAD

**Issue by silvanarnet** [geosigno/simpleParallax.js#62]
Would it be possible to add a "opacity" option?

**Comment by geosigno** [comment]
What would the opacity setting do?

**Comment by silvanarnet** [comment]
Maybe you know the scrollreveal package. There you can set an opacity. When the specified Element enters the viewport, it changes the opacity for example from 0.2 to 1. Especially for Elements with overflow, this effect can look really nice.
I've made a sample here: https://jmp.sh/f3Y1jBC

**Comment by silvanarnet** [comment]
btw. thank you for your awesome package!

**Comment by geosigno** [comment]
In my opinion, it is better to keep this option separated from the plugin. This plugin tries to keep as simple as it could be.
And this could be easily added with another plugin, such as scrollreveal or others
