### ISSUE TITLE
How to set completely still parallax effect?

### ISSUE THREAD

**Issue by tomasts248** [geosigno/simpleParallax.js#65]
Like this one : https://www.w3schools.com/howto/tryhow_css_parallax_demo.htm

**Comment by geosigno** [comment]
I'm not sure to understand what you need. You mean a 100% width parallax? If so, some CSS will do the trick.
If you mean a parallax with background images, then it simply won't work with simpleParallax. Have a parallax effect on image tag (versus background image css property) was the primary motivation for the creation of that plugin. If you want parallax with background images, you'll find what you need quite easily on google.

**Comment by tomasts248** [comment]
I meant that the image doesn't move at all. I do need it for an image tag
