### ISSUE TITLE
Can this be used to parallax section backgound image?

### ISSUE THREAD

**Issue by jattwood** [geosigno/simpleParallax.js#71]
Great script thank you!

I have this currently working well for individual images, however, I am trying to implement this to parallax a background image for a section. If I define my section as a custom wrapper and then include the image directly after and set the image width:100%; height:auto; in order to cover the section as a background might, the height of the section auto expands to the height of the image; I want the height to remain the height of the section as defined by the containing content. Any suggestions? If this is possible it might be good to include this as an example. Thanks!

**Comment by sergiovieira** [comment]
You can add position:relative to the container section and then:

`position: absolute
        top: 0
        left: 0
        width: 100%
        height: 100%
        line-height: 0`

**Comment by jattwood** [comment]
Great - thank you. Working!
