### ISSUE TITLE
Parallax Speed

### ISSUE THREAD

**Issue by sergiovieira** [geosigno/simpleParallax.js#81]
Hi!

I installed this in a project as this looked really simple and a really clean solution. :)

What I need it for is to have some background images in sections appear to be in the background.

The problem is that I can't find a setting to change the speed of the movement, as you can normally find in all parallax scripts.

As it is the image is moving faster than the scrolling which is the opposite of what I need. For a parallax effect to work as in real life, the background should be moving slower than the foreground. Without a speed setting I cannot control this.

Am I missing something here? :)

Thanks!

**Comment by geosigno** [comment]
The speed is calculated via the _scale_ parameter. The higher it is, the faster it is.
