### ISSUE TITLE
Error 404. All modules failed to load on vanilla HTML and JS

### ISSUE THREAD

**Issue by TheConceptBoy** [geosigno/simpleParallax.js#88]
Good day. 
I'm using this extention in a very basic case. just HTML and JS. I get the following errors in console:

simpleParallax.js:5 GET https://depotof.universalideas.ca/scripts/tools/parallax/instances/parallax net::ERR_ABORTED 404
simpleParallax.js:3 GET https://depotof.universalideas.ca/scripts/tools/parallax/helpers/convertToArray net::ERR_ABORTED 404
simpleParallax.js:1 GET https://depotof.universalideas.ca/scripts/tools/parallax/helpers/isSupportedBrowser net::ERR_ABORTED 404
simpleParallax.js:2 GET https://depotof.universalideas.ca/scripts/tools/parallax/helpers/viewport net::ERR_ABORTED 404

I have simply dropped the files for simpleParrallax.js into the web folder. All the instructions point to packet installation for various platforms but mention nothing about good old drag and drop users.

**Comment by TheConceptBoy** [comment]
I had to add .js to all the import messages like this:
import { viewport } from '../helpers/viewport.js';

but now, albeit it does not complain, I still get the error:
index.js:7 Uncaught ReferenceError: simpleParallax is not defined

**Comment by TheConceptBoy** [comment]
Gonna have to use the publicly hosted lib for now.

**Comment by geosigno** [comment]
Should be fixed with latest version.
