### ISSUE TITLE
Tips if i dont want to scale but still have the parallax speed

### ISSUE THREAD

**Issue by ohabash** [geosigno/simpleParallax.js#96]
Wondering if there is a way to control the zoom and translate separately? I want to translate faster without having to zoom

**Comment by esion-net** [comment]
Just stubled upon your question and after looking at the code I found an option:
`overflow: true`
This skips adding the 'scale' attribute and only adds the translate. You'll have to add 'scale' with css yourself.

Example:
`new simpleParallax(images, { scale: 1.4, overflow: true });`

**Comment by geosigno** [comment]
There is no way to control scale (zoom) and translation separately. simpleParallax was built based on the relationship between these two.
