### ISSUE TITLE
iOS 15 Safari issue

### ISSUE THREAD

**Issue by DimitrijRees** [geosigno/simpleParallax.js#97]
There seems to be an issue on iOS 15 Safari with it's new navigation bar and simpleParallax. The parallax images are "jumping" while scrolling through. Maybe because the body is being affected by the navigation bar on scroll? The issue also persists on the demo page: https://simpleparallax.com/#example-max-transition 

It's only on Safari. When creating a standalone app of the website on iOS 15 the issue is gone.

Already tried to set the delay to "0". But if you scroll quickly it's still jumping. Other than that it seemed to be slightly jittering.

**Comment by geosigno** [comment]
This is fixed with latest version.
